# Generated by Django 5.1.4 on 2025-03-20 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0003_eventcategory_raceevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Team Departments',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the team member', max_length=200)),
                ('role', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='team/')),
                ('bio', models.TextField()),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='Website.teamdepartment')),
            ],
            options={
                'verbose_name_plural': 'Team Members',
                'ordering': ['department', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMemberSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='Website.teammember')),
            ],
            options={
                'verbose_name_plural': 'Team Member Skills',
            },
        ),
    ]
